### ISSUE TITLE
Installation fails with pip 18.1

### ISSUE THREAD

**Issue by nomaster** [napalm-automation-community/napalm-vyos#28]
Installation fails when using pip 18.1 (with Python 3.6 in CentOS 7)

```shell
[vagrant@default ~]$ pip3 --version
pip 18.1 from /usr/local/lib/python3.6/site-packages/pip-18.1-py3.6.egg/pip (python 3.6)
[vagrant@default ~]$ pip3 install --user napalm-vyos
Collecting napalm-vyos
  Using cached https://files.pythonhosted.org/packages/e0/ff/2d70e5c7b9925688e000bcc89e140c3bddb61868b1b6cb25414080390700/napalm-vyos-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kh0bects/napalm-vyos/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-kh0bects/napalm-vyos/
```

**Comment by zachyordy** [comment]
+1 on Ubuntu 16.04.5 LTS with Python 3.5.2 and pip 19.0.1:

```
Collecting napalm-vyos
  Using cached https://files.pythonhosted.org/packages/e0/ff/2d70e5c7b9925688e000bcc89e140c3bddb61868b1b6cb25414080390700/napalm-vyos-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wkgvc_u0/napalm-vyos/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ImportError: No module named 'pip.req'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-wkgvc_u0/napalm-vyos/
```

**Comment by ppieprzycki** [comment]
Hi
now you should be able to install napalm-vyos with a newer version of the pip.

**Comment by nomaster** [comment]
Yes, I can confirm successful install with pip 19.0.2 (Python 3.7.0). Thanks!
